/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "N-110228-g4dffa564d1-20230411"
#endif /* AVUTIL_FFVERSION_H */
